### ISSUE TITLE
[FEAT] 회원가입 기능 구현

### ISSUE THREAD

**Issue by kssumin** [Step3-kakao-tech-campus/Team11_BE#1]
### ✨ Describe

자체 회원 가입 기능을 구현합니다.

### ✅ Tasks

- [x] 유저의 이메일, 닉네임, 비밀번호를 받는다. 
- [x] 유저는 이메일 중복 검사를 한 이후 해당 이메일을 사용할 수 있다.
- [x] 유저는 이메일 제약조건을 만족한 경우 해당 이메일을 사용할 수 있다.
- [x] 유저는 닉네임 중복 검사를 한 이후 해당 닉네임을 사용할 수 있다.
- [x] 유저는 비밀번호 제약조건을 만족한 경우 해당 비밀번호를 사용할 수 있다.

### 🕰️ Estimated Time of Completion

6h

### 🙋🏻 More

* 확장 가능성 고려하기
* 추후 Oauth 로그인할 때 사용자 정보를 추가적으로 받을 수도 있음 해당 사항 고려하기
