### ISSUE TITLE
[REFACTOR] 배포환경 추가

### ISSUE THREAD

**Issue by jinwooseok** [Step3-kakao-tech-campus/Team11_BE#104]
### 🔨 Describe

크램폴린에 배포를 하기 위해 설정을 추가하거나 변경함.

### ✅ Tasks

- [x] k8s 추가
- [x] application.yml dev 변경
- [x] dockerfile 설정 변경
- [x] build.gradle mariadb 의존성 추가
