### ISSUE TITLE
[FEAT] 투표 취소 시 해당 유저의 댓글 삭제

### ISSUE THREAD

**Issue by kssumin** [Step3-kakao-tech-campus/Team11_BE#106]
### ✨ Describe

투표 취소 시 해당 유저의 댓글을 삭제합니다.

### ✅ Tasks

- [ ] 투표 취소 시 해당 유저 댓글 삭제
- [ ] 별도의 thread에서 실행
- [ ] 테스트 코드 작성

### 🕰️ Estimated Time of Completion

1 day
