### ISSUE TITLE
[FEAT] 비로그인 사용자 접근 가능 기능

### ISSUE THREAD

**Issue by kssumin** [Step3-kakao-tech-campus/Team11_BE#115]
### ✨ Describe

로그인 한 사용자면 토큰을 추출하고, 비로그인 사용자면 에러는 안 터지도록 합니다.

### ✅ Tasks

- [ ] Login 어노테이션의 속성으로 필수, 논필수를 전달받습니다.
- [ ] 필수면 토큰이 없을 시 에러를 던집니다.(로그인 사용자만 접근 가능)
- [ ] 논필수시 토큰이 있으면 토큰을 파싱하여 사용자 정보를 넘깁니다.
- [ ] 논필수 시 토큰이 없으면 에러는 던지지 않고 비로그인 사용자로 정보를 넘깁니다.

### 🕰️ Estimated Time of Completion

1week...

시험기간 이슈...^^

### 🙋🏻 More

최대한 빨리 할게요...
