### ISSUE TITLE
[FEAT] 투표 조회 기능 구현(페이지)

### ISSUE THREAD

**Issue by PHS00** [Step3-kakao-tech-campus/Team11_BE#15]
### ✨ Describe

사용자는 투표를 조회할 수 있다

### ✅ Tasks

- [ ] 메인페이지 투표 조회 (진행중인 투표) (정렬순 : default = 최신순, 인기순)
- [ ] 종료된 페이지 투표 조회 (완료된 투표) (정렬순 : default = 최신순, 인기순)
- [ ] 마이페이지 응답한 투표 조회
- [ ] 마이페이지 등록한 투표 조회

### 🕰️ Estimated Time of Completion

1주일??
