### ISSUE TITLE
[FEAT] decision 수정

### ISSUE THREAD

**Issue by kssumin** [Step3-kakao-tech-campus/Team11_BE#154]
### ✨ Describe

decision을 수정합니다.

### ✅ Tasks

- [ ] 해당 투표에 대해 이미 한 옵션 번호 확인
- [ ] 해당 옵션 count  -- 처리
- [ ] 새로운 옵션 count ++ 처리

### 🕰️ Estimated Time of Completion

1h
