### ISSUE TITLE
[REFACTOR] test 점검 및 상태코드 점검

### ISSUE THREAD

**Issue by jinwooseok** [Step3-kakao-tech-campus/Team11_BE#184]
### 🔨 Describe

테스트 커버리지를 늘리고 기존에 잘못 설계했던 테스트들을 변경합니다.

### ✅ Tasks

- [x] 접근자에 영향을 주던 기존 테스트 코드를 변경
- [x] 상태 코드 점검
- [x] 테스트 커버리지 업업 100%를 향하여
