### ISSUE TITLE
[FEAT] 무한스크롤 시 사용할 Response 추가

### ISSUE THREAD

**Issue by kssumin** [Step3-kakao-tech-campus/Team11_BE#27]
### ✨ Describe

* 무한스크롤 시 사용할 Response 추가합니다.

### ✅ Tasks

- [x] data
- [ ] 현재 페이지 데이터 개수
- [x]  다음 슬라이스 존재 여부
- [x] 이전 슬라이스 존재여부
### 🕰️ Estimated Time of Completion

0.5h
