### ISSUE TITLE
[REFACTOR] comment 수정

### ISSUE THREAD

**Issue by jinwooseok** [Step3-kakao-tech-campus/Team11_BE#29]
### 🔨 Describe

1. 부족한 부분을 보완하기 위한 리팩토링
2. 예외처리 보완을 위한 리팩토링
3. 테스트 추가를 위한 리팩토링

### ✅ Tasks

- [x] 9가지 원칙을 참고해 리팩토링
- [x] 멘토링 조언에 따라 update로직 리팩토링
- [x] 다른 패키지의 entity를 참조해 예외처리 추가
- [ ] 테스트 추가 

### 🕰️ Estimated Time of Completion

??
