### ISSUE TITLE
[FEAT] 투표 생성 기능

### ISSUE THREAD

**Issue by PHS00** [Step3-kakao-tech-campus/Team11_BE#3]
### ✨ Describe

유저는 투표 생성할 수 있다

### ✅ Tasks

- [x] 유저는 투표 제목을 입력한다
- [x] 유저는 투표 상세 내용을 입력한다
- [x] 유저는 선택 옵션을 최소 2개 ~ 최대 6개까지 설정할 수 있다
- [ ] 유저는 선택 옵션에 사진을 추가할 수 있다
- [x] 유저는 카테고리를 설정할 수 있다 (디폴트 전체)
- [x] 유저는 마감 시간을 설정할 수 있다 (디폴트 전체)
