### ISSUE TITLE
[FEAT] 투표 참여 및 참여 취소 구현

### ISSUE THREAD

**Issue by kssumin** [Step3-kakao-tech-campus/Team11_BE#67]
### ✨ Describe

투표 참여 불참여를 구현합니다.

주의할 점은 투표 참여시 해당 option count를 증가시키고
vote count 또한 증가시켜야 합니다.

### ✅ Tasks

- [x] 옵션 참여
   - [x] option count 증가
   - [x] vote count 증가
- [x] 옵션 참여 취소
  - [x] option count 감소
  - [x] vote count 감소

### 🕰️ Estimated Time of Completion

1day
